2023-11-30 13:19:54,002, ERROR: Exception on /reset_password/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNldF9wYXNzd29yZCI6NSwiZXhwIjoxNzAxMzI1NjgyLjQwOTkxNTd9.juu2Rso7-sHu69fos1wncOSdBMKjJS4xLYnTyPCg4K0 [GET] [in /home/dhanumurti/Project/python/flaskblog/.venv/lib/python3.11/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/dhanumurti/Project/python/flaskblog/.venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dhanumurti/Project/python/flaskblog/.venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dhanumurti/Project/python/flaskblog/.venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dhanumurti/Project/python/flaskblog/.venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dhanumurti/Project/python/flaskblog/app/routes.py", line 185, in reset_password
    return render_template('reset_password.html', form=form)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dhanumurti/Project/python/flaskblog/.venv/lib/python3.11/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dhanumurti/Project/python/flaskblog/.venv/lib/python3.11/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dhanumurti/Project/python/flaskblog/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/dhanumurti/Project/python/flaskblog/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/dhanumurti/Project/python/flaskblog/app/templates/reset_password.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/home/dhanumurti/Project/python/flaskblog/app/templates/base.html", line 34, in top-level template code
    {% block content %} {% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dhanumurti/Project/python/flaskblog/app/templates/reset_password.html", line 9, in block 'content'
    {{ form.password(size-32) }}<br>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'size' is undefined
2023-11-30 13:21:01,304, ERROR: Exception on /reset_password/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNldF9wYXNzd29yZCI6NSwiZXhwIjoxNzAxMzI1NjgyLjQwOTkxNTd9.juu2Rso7-sHu69fos1wncOSdBMKjJS4xLYnTyPCg4K0 [GET] [in /home/dhanumurti/Project/python/flaskblog/.venv/lib/python3.11/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/dhanumurti/Project/python/flaskblog/.venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dhanumurti/Project/python/flaskblog/.venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dhanumurti/Project/python/flaskblog/.venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dhanumurti/Project/python/flaskblog/.venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dhanumurti/Project/python/flaskblog/app/routes.py", line 185, in reset_password
    return render_template('reset_password.html', form=form)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dhanumurti/Project/python/flaskblog/.venv/lib/python3.11/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dhanumurti/Project/python/flaskblog/.venv/lib/python3.11/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dhanumurti/Project/python/flaskblog/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/dhanumurti/Project/python/flaskblog/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/dhanumurti/Project/python/flaskblog/app/templates/reset_password.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/home/dhanumurti/Project/python/flaskblog/app/templates/base.html", line 34, in top-level template code
    {% block content %} {% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dhanumurti/Project/python/flaskblog/app/templates/reset_password.html", line 9, in block 'content'
    {{ form.password(size=32) }}<br>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'size' is undefined
2023-11-30 13:21:08,097, INFO: Server logs [in /home/dhanumurti/Project/python/flaskblog/app/__init__.py:32]
2023-11-30 16:26:43,435, INFO: Server logs [in /home/dhanumurti/Project/python/flaskblog/app/__init__.py:32]
2023-11-30 16:28:38,804, INFO: Server logs [in /home/dhanumurti/Project/python/flaskblog/app/__init__.py:32]
2023-11-30 16:30:31,636, INFO: Server logs [in /home/dhanumurti/Project/python/flaskblog/app/__init__.py:32]
2023-11-30 16:35:06,240, INFO: Server logs [in /home/dhanumurti/Project/python/flaskblog/app/__init__.py:32]
2023-11-30 16:39:33,442, INFO: Server logs [in /home/dhanumurti/Project/python/flaskblog/app/__init__.py:32]
2023-11-30 16:40:22,698, INFO: Server logs [in /home/dhanumurti/Project/python/flaskblog/app/__init__.py:32]
2023-11-30 16:43:33,228, INFO: Server logs [in /home/dhanumurti/Project/python/flaskblog/app/__init__.py:32]
2023-11-30 16:45:15,115, INFO: Server logs [in /home/dhanumurti/Project/python/flaskblog/app/__init__.py:32]
2023-11-30 16:45:17,681, ERROR: Exception on /reset_password/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNldF9wYXNzd29yZCI6NSwiZXhwIjoxNzAxMzM4MDIxLjA5ODI2Mn0.Fb3owwztJdQy6r4-2FOqNan_nXRFKA6-2a11AOfAoPI [POST] [in /home/dhanumurti/Project/python/flaskblog/.venv/lib/python3.11/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/dhanumurti/Project/python/flaskblog/.venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dhanumurti/Project/python/flaskblog/.venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dhanumurti/Project/python/flaskblog/.venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dhanumurti/Project/python/flaskblog/.venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dhanumurti/Project/python/flaskblog/app/routes.py", line 185, in reset_password
    return render_template('reset_password.html', form=form)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dhanumurti/Project/python/flaskblog/.venv/lib/python3.11/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dhanumurti/Project/python/flaskblog/.venv/lib/python3.11/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dhanumurti/Project/python/flaskblog/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/dhanumurti/Project/python/flaskblog/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/dhanumurti/Project/python/flaskblog/app/templates/reset_password.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/home/dhanumurti/Project/python/flaskblog/app/templates/base.html", line 34, in top-level template code
    {% block content %} {% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dhanumurti/Project/python/flaskblog/app/templates/reset_password.html", line 8, in block 'content'
    {{ form.password.label }}<br>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dhanumurti/Project/python/flaskblog/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'app.forms.ResetPasswordForms object' has no attribute 'password'
